import Head from "next/head";
import Link from "next/link";

export default function Header() {
  return (
    <div>
      <Head>
        <title>__7_oooomi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          <Link href="/">Iam</Link>
        </h1>
        <div>
          <Link href="/about">about</Link>
        </div>
        <div>
          <Link href="/works">works</Link>
        </div>
        <div>
          <Link href="/contact">contact</Link>
        </div>
        <div>
          <Link href="/login">login</Link>
        </div>
      </main>
    </div>
  );
}
