import Head from "next/head";
import Link from "next/link";
import Nav from "react-bootstrap/Nav";
import styles from "../../styles/Home.module.css";

export default function Header() {
  return (
    <div>
      <Head>
        <title>__7_oooomi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {" "}
        <Nav className={styles.header}>
          <h1>
            <Link href="/">portfolio</Link>
          </h1>

          <Nav.Item>
            <Nav.Link style={{ color: "black" }} href="/about">
              about
            </Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link style={{ color: "black" }} href="/works">
              works
            </Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link style={{ color: "black" }} href="/contact">
              contact
            </Nav.Link>
          </Nav.Item>
          <Nav.Item>
            <Nav.Link style={{ color: "black" }} href="/login">
              login
            </Nav.Link>
          </Nav.Item>
        </Nav>
      </main>
    </div>
  );
}
